name: Deploy NGINX Webserver

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t cgi-nginx .

      - name: Run container
        run: |
          docker stop cgi-nginx || true
          docker run -d -p 8080:80 --name cgi-nginx cgi-nginx