name: Deploy NGINX
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Verify files
        run: |
          ls -la
          ls -la html/

      - name: Build Docker image
        run: docker build -t cgi-nginx .

      - name: Run container
        run: |
          docker stop cgi-nginx || true
          docker run -d -p 8080:80 --name cgi-nginx cgi-nginx