name: Deploy NGINX

on: 
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate structure
        run: |
          echo "Current structure:"
          ls -R
          [ -f Dockerfile ] || exit 1
          [ -d html ] || exit 1

      - name: Build
        run: docker build -t cgi-nginx .

      - name: Deploy
        run: |
          docker rm -f cgi-nginx || true
          docker run -d -p 8080:80 --name cgi-nginx cgi-nginx