name: Deploy NGINX
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate structure
        run: |
          echo "Contents:"
          ls -la
          [ -f Dockerfile ] || exit 1
          [ -d html ] || exit 1

      - name: Build and deploy
        run: |
          docker build -t cgi-nginx .
          docker rm -f cgi-nginx || true
          docker run -d -p 8080:80 --name cgi-nginx cgi-nginx