name: Auto Deploy NGINX

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Change to cgi-task3 directory
      run: cd cgi-task3

    - name: Build Docker image
      working-directory: ./cgi-task3
      run: docker build -t cgi-nginx -f Dockerfile .

    - name: Run Docker container
      working-directory: ./cgi-task3
      run: |
        docker stop cgi-nginx || true
        docker rm cgi-nginx || true
        docker run -d -p 8080:80 --name cgi-nginx cgi-nginx
