name: Deploy NGINX

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Verify files
        run: |
          echo "Current structure:"
          ls -la
          [ -f Dockerfile ] || { echo "ERROR: Missing Dockerfile"; exit 1; }
          [ -d html ] || { echo "ERROR: Missing html/"; exit 1; }

      - name: Build and deploy
        run: |
          docker build -t cgi-nginx .
          docker run -d -p 8080:80 --name cgi-nginx cgi-nginx